### Dicision Tree

> classification algorithm...

> Its follows tree like structure to predict the o/p

<img src="https://miro.medium.com/v2/resize:fit:1430/1*rSQIIAboJftqAv_BReNipg.png">

In [1]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_excel("/content/tennis_anyone_1000 (5).xlsx")

In [7]:
df.head()

  Day ID   Outlook Temperature Humidity    Wind Play Tennis
0  Day_1  Overcast        Cool   Normal  Strong         Yes
1  Day_2      Rain        Mild     High    Weak         Yes
2  Day_3  Overcast         Hot   Normal    Weak         Yes
3  Day_4     Sunny        Mild   Normal  Strong         Yes
4  Day_5     Sunny        Mild     High    Weak          No

In [11]:
df.columns

Index(['Outlook', 'Temperature', 'Humidity', 'Wind', 'Play Tennis'], dtype='object')

In [8]:
df.drop(columns='Day ID',inplace=True)

In [17]:
df.nunique()

Outlook        3
Temperature    3
Humidity       2
Wind           2
Play Tennis    2
dtype: int64

In [9]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['Outlook']=le.fit_transform(df['Outlook']) #overcost-0,rain-1,sunny-2
df['Temperature']=le.fit_transform(df['Temperature'])#cool-0,mild-2,hot-1
df['Humidity']=le.fit_transform(df['Humidity'])#normal-0,high=1
df['Wind']=le.fit_transform(df['Wind'])#strong-0,weak-1
df['Play Tennis']=le.fit_transform(df['Play Tennis'])#yes=1,no-0

In [18]:
df.head()

   Outlook  Temperature  Humidity  Wind  Play Tennis
0        0            0         1     0            1
1        1            2         0     1            1
2        0            1         1     1            1
3        2            2         1     0            1
4        2            2         0     1            0

In [19]:
### How to cheeck number of yes nad no rows in dataset

df.groupby('Play Tennis').count()

             Outlook  Temperature  Humidity  Wind
Play Tennis
0                349          349       349   349
1                651          651       651   651

In [20]:
### renaming the columns
df.rename(columns={'play Tennies':'playTannies'},inplace=True)

In [21]:
df['Play Tennis'].value_counts()

Play Tennis
1    651
0    349
Name: count, dtype: int64

In [22]:
df.shape

(1000, 5)

In [23]:
#### splitting dataset verticially(input/output)
x = df.iloc[:,0:-1]
y = df.iloc[:,-1]

In [26]:
## splitting dataset horizontally(train and test set(20%))
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=1)

In [27]:
### using Dicision Tree model
from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier()
dt

DecisionTreeClassifier()

In [28]:
# training the model
dt.fit(x_train,y_train)

DecisionTreeClassifier()

In [29]:
### predict

predict = dt.predict(x_test)

In [30]:
## evaluating model
from sklearn.metrics import classification_report

print(classification_report(y_test,predict))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        69
           1       1.00      1.00      1.00       131

    accuracy                           1.00       200
   macro avg       1.00      1.00      1.00       200
weighted avg       1.00      1.00      1.00       200

>>Dicision Tree accuracy with 100%